overrides:
  axios@<0.21.1: '>=0.21.1'
  axios@<0.21.2: '>=0.21.2'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  debug@>=4.0.0 <4.3.1: '>=4.3.1'
  follow-redirects@<1.14.7: '>=1.14.7'
  follow-redirects@<1.14.8: '>=1.14.8'
  follow-redirects@<1.15.4: '>=1.15.4'
  follow-redirects@<=1.15.5: '>=1.15.6'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
  react-router@>=7.0.0 <7.9.6: '>=7.9.6'
  react-router@>=7.0.0 <=7.11.0: '>=7.12.0'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@=7.5.1: '>=7.5.2'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  yargs-parser@<=5.0.0: '>=5.0.1'
